# Generated by Django 5.0.7 on 2024-07-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
