# Generated by Django 5.0.7 on 2024-07-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
