# Generated by Django 5.0.7 on 2024-07-29 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
